language: csharp
mono: none
os: windows

solution: src/dotnet-structuring/dotnet-structuring.csproj

before_script:
    - export PATH="$PATH:$HOME/.dotnet/tools"

script:
    - choco install dotnetcore-sdk
    - choco install opencover.portable
    - choco install codecov
    - dotnet --version
    - dotnet restore
    - dotnet build src/dotnet-structuring/dotnet-structuring.csproj
    - OpenCover.Console.exe -register:administrator -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:test -output:".\coverage.xml" -oldstyle

install:
    - dotnet restore src/dotnet-structuring/dotnet-structuring.csproj

cache:
  directories:
    - "$HOME/.nuget/packages"
    - "$HOME/.local/share/NuGet/Cache"
after_success:
    - codecov -f "coverage.xml"